# Generated by Django 5.2.17 on 2026-09-11 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("governance", "0023_plan_teams_included"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegionalPrice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("region_code", models.CharField(max_length=10)),
                ("price", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("extra_team_price", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="regional_prices",
                        to="governance.plan",
                    ),
                ),
            ],
            options={
                "ordering": ["plan_id", "region_code"],
                "constraints": [
                    models.UniqueConstraint(fields=("plan", "region_code"), name="unique_plan_region_price")
                ],
            },
        ),
    ]
