# Generated by Django 5.2.17 on 2026-09-12 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_user_mfa_enabled"),
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationBillingProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("bank_name", models.CharField(blank=True, max_length=200)),
                ("account_title", models.CharField(blank=True, max_length=200)),
                ("account_number", models.CharField(blank=True, max_length=100)),
                ("swift_code", models.CharField(blank=True, max_length=50)),
                ("payment_note", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Organization billing profile",
                "verbose_name_plural": "Organization billing profile",
            },
        ),
        migrations.CreateModel(
            name="DepartmentBillingProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("company_name", models.CharField(blank=True, max_length=200)),
                ("country", models.CharField(blank=True, max_length=10)),
                ("billing_address", models.TextField(blank=True)),
                ("tax_id", models.CharField(blank=True, max_length=100)),
                ("is_tax_exempt", models.BooleanField(default=False)),
                (
                    "custom_tax_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Percent. Overrides the country's default tax rate when set.",
                        max_digits=5,
                        null=True,
                    ),
                ),
                ("auto_generate_invoices", models.BooleanField(default=True)),
                (
                    "reminder_days_after_due",
                    models.PositiveIntegerField(
                        choices=[(0, "No reminder"), (3, "3 days after due"), (7, "7 days after due")], default=0
                    ),
                ),
                (
                    "department",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billing_profile",
                        to="accounts.department",
                    ),
                ),
            ],
        ),
    ]
