# Generated by Django 5.2.17 on 2026-09-12 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0003_invoice"),
    ]

    operations = [
        migrations.RenameField(
            model_name="regionalprice",
            old_name="extra_team_price",
            new_name="extra_seat_price",
        ),
    ]
