# Generated by Django 5.2.17 on 2026-09-12 04:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0004_rename_extra_team_price_regionalprice_extra_seat_price"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="recipient_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoices",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="submitted_proof_image",
            field=models.ImageField(blank=True, null=True, upload_to="invoice_proofs/"),
        ),
        migrations.AddField(
            model_name="invoice",
            name="submitted_transaction_id",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="invoice",
            name="verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[("unpaid", "Unpaid"), ("pending_verification", "Pending verification"), ("paid", "Paid")],
                default="unpaid",
                max_length=25,
            ),
        ),
    ]
