# Generated by Django 5.2.17 on 2026-09-12 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0005_invoice_recipient_user_invoice_submitted_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="line_items",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
