# Generated by Django 5.2.17 on 2026-09-12 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0006_invoice_line_items"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="seats_billed",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
