# Generated by Django 5.2.17 on 2026-09-12 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_department_plan"),
        ("billing", "0007_invoice_seats_billed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoices",
                to="accounts.department",
            ),
        ),
    ]
