# Generated by Django 5.2.17 on 2026-09-12 11:15

import secrets

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _backfill_share_tokens(apps, schema_editor):
    Invoice = apps.get_model("billing", "Invoice")
    for invoice in Invoice.objects.filter(share_token__isnull=True):
        invoice.share_token = secrets.token_urlsafe(24)
        invoice.save(update_fields=["share_token"])


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0009_seed_daily_invoice_sweep_schedule"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="share_token",
            field=models.CharField(blank=True, editable=False, max_length=48, null=True, unique=True),
        ),
        migrations.CreateModel(
            name="UserBillingProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("company_name", models.CharField(blank=True, max_length=200)),
                ("phone_number", models.CharField(blank=True, max_length=32)),
                ("billing_address", models.TextField(blank=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billing_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RunPython(_backfill_share_tokens, migrations.RunPython.noop),
    ]
