# Generated by Django 5.2.17 on 2026-09-12 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0010_invoice_share_token_userbillingprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="reminder_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
