# Generated by Django 5.2.17 on 2026-09-19 01:53

import billing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0014_set_extra_seat_price_for_known_plans"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="submitted_proof_image",
            field=models.ImageField(blank=True, null=True, upload_to=billing.models._invoice_proof_upload_path),
        ),
    ]
