# Generated by Django 5.2.17 on 2026-09-24 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0016_invoice_refund_amount_invoice_refunded_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="duration_months",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
