# Generated by Django 5.2.17 on 2026-09-24 11:59

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0017_invoice_duration_months"),
        ("governance", "0040_seed_maintenance_schedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="credit_applied",
            field=models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=10),
        ),
        migrations.AddField(
            model_name="invoice",
            name="is_fixed_term",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="invoice",
            name="previous_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="governance.plan",
            ),
        ),
    ]
