# Generated by Django 5.2.17 on 2026-09-03 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Provider",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50)),
                ("slug", models.SlugField(unique=True)),
                (
                    "adapter_type",
                    models.CharField(
                        choices=[
                            ("anthropic", "Anthropic"),
                            ("openai_compatible", "OpenAI-compatible"),
                            ("gemini", "Google Gemini"),
                        ],
                        max_length=50,
                    ),
                ),
                ("base_url", models.URLField(blank=True)),
                ("api_key_encrypted", models.BinaryField(blank=True, default=b"")),
                ("api_key_last4", models.CharField(blank=True, max_length=4)),
                ("is_connected", models.BooleanField(default=False)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_sync_status",
                    models.CharField(
                        choices=[("never", "Never synced"), ("success", "Success"), ("failed", "Failed")],
                        default="never",
                        max_length=20,
                    ),
                ),
                ("last_sync_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ProviderModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "model_id",
                    models.CharField(help_text="Raw model identifier from the provider's own API.", max_length=100),
                ),
                ("display_name", models.CharField(blank=True, max_length=100)),
                ("is_enabled", models.BooleanField(default=False)),
                ("is_new", models.BooleanField(default=True)),
                ("first_seen_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
                ("is_retired", models.BooleanField(default=False)),
                ("input_price_per_mtok", models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ("output_price_per_mtok", models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="models", to="providers.provider"
                    ),
                ),
            ],
            options={
                "ordering": ["provider__name", "model_id"],
                "constraints": [
                    models.UniqueConstraint(fields=("provider", "model_id"), name="unique_model_id_per_provider")
                ],
            },
        ),
    ]
