# Generated by Django 5.2.17 on 2026-09-03 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("providers", "0002_seed_providers"),
    ]

    operations = [
        migrations.AddField(
            model_name="providermodel",
            name="tier",
            field=models.CharField(
                choices=[("economy", "Economy"), ("default", "Default"), ("premium", "Premium")],
                default="default",
                max_length=20,
            ),
        ),
    ]
