# Generated by Django 5.2.17 on 2026-09-04 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("providers", "0004_seed_provider_resync_schedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="providermodel",
            name="is_manager_assignable",
            field=models.BooleanField(default=False),
        ),
    ]
