# Generated by Django 5.2.17 on 2026-09-04 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("providers", "0005_providermodel_is_manager_assignable"),
    ]

    operations = [
        migrations.AddField(
            model_name="provider",
            name="region",
            field=models.CharField(
                choices=[("us", "United States"), ("eu", "European Union"), ("global", "Global / other")],
                default="global",
                max_length=10,
            ),
        ),
    ]
