# Generated by Django 5.2.17 on 2026-09-04 22:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("providers", "0006_provider_region"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="provider",
            name="approval_status",
            field=models.CharField(
                choices=[("approved", "Approved"), ("pending", "Pending compliance review")],
                default="approved",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="provider",
            name="connected_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
