# Generated by Django 5.2.17 on 2026-09-04 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("providers", "0007_provider_approval_status_provider_connected_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="provider",
            name="trains_on_data",
            field=models.BooleanField(default=False),
        ),
    ]
