# Generated by Django 5.2.17 on 2026-09-05 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("providers", "0008_provider_trains_on_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="providermodel",
            name="is_playground_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
