# Generated by Django 5.2.17 on 2026-09-06 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("providers", "0009_providermodel_is_playground_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="providermodel",
            name="is_domain_generator_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
