# Generated by Django 5.2.17 on 2026-09-12 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("providers", "0010_providermodel_is_domain_generator_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="providermodel",
            name="supports_vision",
            field=models.BooleanField(default=False),
        ),
    ]
