# Generated by Django 5.2.17 on 2026-09-17 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("providers", "0011_providermodel_supports_vision"),
    ]

    operations = [
        migrations.AddField(
            model_name="provider",
            name="color_hex",
            field=models.CharField(
                blank=True,
                help_text="e.g. #1f9254. Leave blank to auto-generate a distinct color from the provider's slug.",
                max_length=7,
            ),
        ),
    ]
