from django.urls import path

from governance import views

app_name = "governance"

urlpatterns = [
    path("", views.DashboardView.as_view(), name="dashboard"),
    path(
        "dashboard/playground-models/<int:model_id>/toggle/",
        views.toggle_playground_model,
        name="toggle_playground_model",
    ),
    path(
        "dashboard/domain-generator-models/<int:model_id>/toggle/",
        views.toggle_domain_generator_model,
        name="toggle_domain_generator_model",
    ),
    path("search/", views.global_search, name="global_search"),
    path("my-team/", views.ManagerDashboardView.as_view(), name="manager_dashboard"),
    path("my-team/models/<int:model_id>/toggle/", views.toggle_team_model, name="toggle_team_model"),
    path("my-team/members/<int:user_id>/remove/", views.remove_team_member, name="remove_team_member"),
    path(
        "my-team/members/<int:user_id>/permissions/",
        views.manager_member_permissions,
        name="manager_member_permissions",
    ),
    path(
        "my-team/members/<int:user_id>/permissions/<int:model_id>/toggle/",
        views.toggle_member_model_permission,
        name="toggle_member_model_permission",
    ),
    path("users/", views.UserListView.as_view(), name="users"),
    path("users/add/", views.add_user, name="add_user"),
    path("users/<int:user_id>/edit/", views.user_edit_form, name="user_edit_form"),
    path("users/<int:user_id>/toggle-active/", views.toggle_user_active, name="toggle_user_active"),
    path("users/<int:user_id>/delete/", views.delete_user, name="delete_user"),
    path("users/<int:user_id>/change-email/", views.change_user_email, name="change_user_email"),
    path("users/<int:user_id>/reset-password/", views.reset_user_password, name="reset_user_password"),
    path("users/<int:user_id>/change-role/", views.change_user_role, name="change_user_role"),
    path("users/<int:user_id>/change-department/", views.change_user_department, name="change_user_department"),
    path("users/<int:user_id>/change-team/", views.change_user_team, name="change_user_team"),
    path("users/<int:user_id>/change-plan/", views.change_user_plan, name="change_user_plan"),
    path("users/bulk-change-plan/", views.bulk_change_plan, name="bulk_change_plan"),
    path("users/<int:user_id>/overrides/", views.UserOverridesView.as_view(), name="user_overrides"),
    path("users/<int:user_id>/overrides/clear/", views.clear_user_overrides_view, name="clear_user_overrides"),
    path("feature-visibility/", views.FeatureVisibilityView.as_view(), name="feature_visibility"),
    path("feature-visibility/mfa-required/toggle/", views.toggle_mfa_required, name="toggle_mfa_required"),
    path("branding/", views.BrandingSettingsView.as_view(), name="branding"),
    path("teams/", views.TeamListView.as_view(), name="teams"),
    path("teams/add/", views.add_team, name="add_team"),
    path("teams/<int:team_id>/delete/", views.delete_team, name="delete_team"),
    path("plans/", views.PlanListView.as_view(), name="plans"),
    path("plans/new/", views.PlanFormView.as_view(), name="plan_new"),
    path("plans/<int:plan_id>/edit/", views.PlanFormView.as_view(), name="plan_edit"),
    path("budget-automation/", views.BudgetAutomationView.as_view(), name="budget_automation"),
    path("budget-automation/<int:plan_id>/update/", views.update_budget_automation, name="update_budget_automation"),
    path("routing-rules/", views.RoutingRuleListView.as_view(), name="routing_rules"),
    path("routing-rules/new/", views.RoutingRuleFormView.as_view(), name="routing_rule_new"),
    path("routing-rules/<int:rule_id>/edit/", views.RoutingRuleFormView.as_view(), name="routing_rule_edit"),
    path("routing-rules/<int:rule_id>/delete/", views.delete_routing_rule, name="delete_routing_rule"),
    path("compliance-routing/", views.ComplianceRoutingView.as_view(), name="compliance_routing"),
    path(
        "compliance-routing/<int:department_id>/update/",
        views.update_department_region_restriction,
        name="update_department_region_restriction",
    ),
    path(
        "retention-provider-approval/",
        views.RetentionProviderApprovalView.as_view(),
        name="retention_provider_approval",
    ),
    path(
        "retention-provider-approval/<int:department_id>/retention/",
        views.update_department_retention,
        name="update_department_retention",
    ),
    path("data-handling/", views.DataHandlingView.as_view(), name="data_handling"),
    path("data-handling/zero-retention/toggle/", views.toggle_zero_retention_only, name="toggle_zero_retention_only"),
    path("data-handling/pii-scanning/toggle/", views.toggle_pii_scanning_enabled, name="toggle_pii_scanning_enabled"),
    path(
        "data-handling/providers/<int:provider_id>/trains-on-data/toggle/",
        views.toggle_provider_trains_on_data,
        name="toggle_provider_trains_on_data",
    ),
    path("data-handling/pii-rules/<int:rule_id>/update/", views.update_pii_rule, name="update_pii_rule"),
    path("capability-limits/", views.CapabilityLimitsView.as_view(), name="capability_limits"),
    path(
        "capability-limits/<int:plan_id>/update/",
        views.update_capability_limits,
        name="update_capability_limits",
    ),
    path("email-logs/", views.EmailLogListView.as_view(), name="email_logs"),
    path("email-logs/settings/update/", views.update_email_settings, name="update_email_settings"),
    path("email-logs/settings/test/", views.send_test_email, name="send_test_email"),
    path("upgrade-requests/", views.UpgradeRequestListView.as_view(), name="upgrade_requests"),
    path("upgrade-requests/<int:request_id>/resolve/", views.resolve_upgrade_request, name="resolve_upgrade_request"),
    path("models/", views.ModelListView.as_view(), name="models"),
    path("models/<int:model_id>/toggle-enabled/", views.toggle_model_enabled, name="toggle_model_enabled"),
    path("models/<int:model_id>/delete/", views.delete_model, name="delete_model"),
    path("models/<int:model_id>/pricing/", views.update_model_pricing, name="update_model_pricing"),
    path("models/<int:model_id>/permissions/", views.ModelPermissionsView.as_view(), name="model_permissions"),
    path("usage/", views.UsageSummaryView.as_view(), name="usage"),
    path("usage/export.csv", views.export_usage_csv, name="export_usage_csv"),
    path("usage/export.xlsx", views.export_usage_xlsx, name="export_usage_xlsx"),
    path("usage/export-monthly-summary.xlsx", views.export_usage_monthly_summary, name="export_usage_monthly_summary"),
    path("limits/", views.LimitListView.as_view(), name="limits"),
    path("limits/new/", views.LimitFormView.as_view(), name="limit_new"),
    path("limits/<int:limit_id>/edit/", views.LimitFormView.as_view(), name="limit_edit"),
    path("limits/<int:limit_id>/delete/", views.delete_limit, name="limit_delete"),
    path("audit-logs/", views.AuditLogListView.as_view(), name="audit_logs"),
    path("feedback/", views.FeedbackListView.as_view(), name="feedback"),
    path("departments/", views.DepartmentListView.as_view(), name="departments"),
    path("departments/add/", views.add_department, name="add_department"),
    path("departments/<int:department_id>/update/", views.update_department, name="update_department"),
    path("departments/<int:department_id>/delete/", views.delete_department, name="delete_department"),
    path("departments/<int:department_id>/system-prompt/", views.SystemPromptView.as_view(), name="system_prompt"),
    path(
        "departments/<int:department_id>/templates/",
        views.DepartmentTemplatesView.as_view(),
        name="department_templates",
    ),
    path(
        "departments/<int:department_id>/templates/<int:template_id>/delete/",
        views.delete_department_template,
        name="delete_department_template",
    ),
]
