# Generated by Django 5.2.17 on 2026-08-27 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(default="New chat", max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ModelConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "provider",
                    models.CharField(choices=[("openai", "OpenAI"), ("anthropic", "Anthropic")], max_length=20),
                ),
                (
                    "model_name",
                    models.CharField(
                        help_text="Exact provider API model identifier, e.g. gpt-4o-mini or claude-sonnet-4-5.",
                        max_length=100,
                    ),
                ),
                (
                    "tier",
                    models.CharField(
                        choices=[("economy", "Economy"), ("default", "Default"), ("premium", "Premium")],
                        default="default",
                        max_length=20,
                    ),
                ),
                (
                    "input_cost_per_1m",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="USD per 1M input tokens. Verify against provider pricing before setting.",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "output_cost_per_1m",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="USD per 1M output tokens. Verify against provider pricing before setting.",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Model is unusable until an admin verifies pricing and enables it here.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["provider", "tier", "model_name"],
                "unique_together": {("provider", "model_name")},
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("role", models.CharField(choices=[("user", "User"), ("assistant", "Assistant")], max_length=20)),
                ("content", models.TextField(blank=True)),
                ("input_tokens", models.PositiveIntegerField(blank=True, null=True)),
                ("output_tokens", models.PositiveIntegerField(blank=True, null=True)),
                ("estimated_cost", models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="messages", to="chat.conversation"
                    ),
                ),
                (
                    "model_used",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="messages",
                        to="chat.modelconfig",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserModelPermission",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_allowed", models.BooleanField(default=True)),
                (
                    "model_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_permissions",
                        to="chat.modelconfig",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="model_permissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "model_config")},
            },
        ),
    ]
