# Generated by Django 5.2.17 on 2026-08-29 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_conversation_deleted_at_conversation_is_deleted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelconfig",
            name="display_name",
            field=models.CharField(
                blank=True,
                help_text="Shown to users instead of the raw model ID. Leave blank to just show the ID.",
                max_length=100,
            ),
        ),
    ]
