# Generated by Django 5.2.17 on 2026-08-30 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0005_seed_model_sync_check_schedule"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="served_from_cache",
            field=models.BooleanField(
                default=False,
                help_text="This reply was served from the Redis response cache instead of calling the provider again - see chat/response_cache.py. tokens/estimated_cost still reflect what the (skipped) call would have cost, for usage-limit accounting; this flag is what the admin cost-saved metric sums over.",
            ),
        ),
        migrations.CreateModel(
            name="MessageFeedback",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("rating", models.CharField(choices=[("up", "Thumbs up"), ("down", "Thumbs down")], max_length=10)),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "message",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="feedback", to="chat.message"
                    ),
                ),
                (
                    "model_used",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="chat.modelconfig",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message_feedback",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
