# Generated by Django 5.2.17 on 2026-09-02 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0007_prompttemplate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="title",
            field=models.CharField(default="New conversation", max_length=200),
        ),
    ]
