# Generated by Django 5.2.17 on 2026-09-03 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0009_message_provider_model_used"),
        ("providers", "0003_providermodel_tier"),
    ]

    operations = [
        migrations.AddField(
            model_name="messagefeedback",
            name="provider_model_used",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="providers.providermodel",
            ),
        ),
    ]
