# Generated by Django 5.2.17 on 2026-09-04 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0011_remove_model_sync_check_schedule"),
        ("providers", "0005_providermodel_is_manager_assignable"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="usermodelpermission",
            unique_together={("user", "model_config")},
        ),
        migrations.AddField(
            model_name="usermodelpermission",
            name="provider_model",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_permissions",
                to="providers.providermodel",
            ),
        ),
        migrations.AlterField(
            model_name="usermodelpermission",
            name="model_config",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_permissions",
                to="chat.modelconfig",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="usermodelpermission",
            unique_together={("user", "model_config"), ("user", "provider_model")},
        ),
        migrations.AddConstraint(
            model_name="usermodelpermission",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("model_config__isnull", False), ("provider_model__isnull", True)),
                    models.Q(("model_config__isnull", True), ("provider_model__isnull", False)),
                    _connector="OR",
                ),
                name="user_model_permission_exactly_one_of_model_config_or_provider_model",
            ),
        ),
    ]
