# Generated by Django 5.2.17 on 2026-09-04 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0012_alter_usermodelpermission_unique_together_and_more"),
        ("providers", "0005_providermodel_is_manager_assignable"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArenaComparison",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="arena_comparisons",
                        to="chat.conversation",
                    ),
                ),
                (
                    "model_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="+", to="providers.providermodel"
                    ),
                ),
                (
                    "model_b",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="+", to="providers.providermodel"
                    ),
                ),
                (
                    "picked",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="chat.message",
                    ),
                ),
                (
                    "response_a",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="arena_as_a", to="chat.message"
                    ),
                ),
                (
                    "response_b",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="arena_as_b", to="chat.message"
                    ),
                ),
                (
                    "user_message",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="arena_comparison", to="chat.message"
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
