# Generated by Django 5.2.17 on 2026-09-12 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0013_arenacomparison"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="stream_token",
            field=models.CharField(blank=True, editable=False, max_length=48, null=True, unique=True),
        ),
    ]
