# Generated by Django 5.2.17 on 2026-09-13 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0014_message_stream_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="attachment_kind",
            field=models.CharField(blank=True, choices=[("image", "Image"), ("document", "Document")], max_length=10),
        ),
    ]
