# Generated by Django 5.2.17 on 2026-09-13 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0015_message_attachment_kind"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="attachment_kind",
            field=models.CharField(
                blank=True, choices=[("image", "Image"), ("document", "Document"), ("video", "Video")], max_length=10
            ),
        ),
    ]
