# Generated by Django 5.2.17 on 2026-09-13 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0016_alter_message_attachment_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="used_research",
            field=models.BooleanField(default=False),
        ),
    ]
