# Generated by Django 5.2.17 on 2026-09-17 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0017_message_used_research"),
        ("providers", "0013_backfill_provider_color_hex"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="last_provider_model",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="providers.providermodel",
            ),
        ),
    ]
