# Generated by Django 5.2.17 on 2026-09-17 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0019_backfill_conversation_last_provider_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="artifact_title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="message",
            name="is_artifact",
            field=models.BooleanField(default=False),
        ),
    ]
