# Generated by Django 5.2.17 on 2026-09-19 01:53

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0021_project_conversation_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="attachment",
            field=models.FileField(blank=True, null=True, upload_to=chat.models._chat_attachment_upload_path),
        ),
    ]
