# Generated by Django 5.2.17 on 2026-09-19 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0022_alter_message_attachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="generation_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="is_generating",
            field=models.BooleanField(default=False),
        ),
    ]
