# Generated by Django 5.2.17 on 2026-09-19 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0023_message_generation_started_at_message_is_generating"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="live_intel",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
