# Generated by Django 5.2.17 on 2026-08-30 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="has_seen_onboarding",
            field=models.BooleanField(
                default=False,
                help_text='Set once the first-login guided tour is completed or skipped. "Replay tour" in Settings resets this to False.',
            ),
        ),
    ]
