# Generated by Django 5.2.17 on 2026-08-30 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_preferred_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="preferred_language",
            field=models.CharField(
                choices=[("en", "English"), ("ur", "اردو"), ("ar", "العربية")],
                default="en",
                help_text="UI label language (not the AI's reply language, which follows the conversation naturally). Set from Settings; see accounts/middleware.py for how this is applied on every request.",
                max_length=10,
            ),
        ),
    ]
