# Generated by Django 5.2.17 on 2026-08-31 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_user_preferred_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="theme_preference",
            field=models.CharField(
                choices=[("light", "Light"), ("dark", "Dark"), ("system", "System")],
                default="system",
                help_text="UI color theme. 'System' follows the OS/browser preference automatically. Set from Settings; see base.html for how this is applied.",
                max_length=10,
            ),
        ),
    ]
