# Generated by Django 5.2.17 on 2026-08-31 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_user_theme_preference"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="department",
            field=models.ForeignKey(
                blank=True,
                help_text="For an Admin, this is what scopes their access. For a SuperAdmin it's unused (unscoped).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="accounts.department",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("user", "User"), ("manager", "Manager"), ("admin", "Admin"), ("superadmin", "SuperAdmin")],
                default="user",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=150)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="teams", to="accounts.department"
                    ),
                ),
                (
                    "manager",
                    models.OneToOneField(
                        blank=True,
                        help_text="Kept in sync with that user's `team` field whenever their role is set to Manager.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_team",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["department__name", "name"],
            },
        ),
        migrations.AddField(
            model_name="user",
            name="team",
            field=models.ForeignKey(
                blank=True,
                help_text="A Manager's own team is tracked via Team.manager instead — this is for team MEMBERSHIP.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="members",
                to="accounts.team",
            ),
        ),
        migrations.AddConstraint(
            model_name="team",
            constraint=models.UniqueConstraint(fields=("department", "name"), name="unique_team_name_per_department"),
        ),
    ]
