# Generated by Django 5.2.17 on 2026-09-02 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_user_department_alter_user_role_team_user_team_and_more"),
        ("chat", "0008_alter_conversation_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="disabled_models",
            field=models.ManyToManyField(
                blank=True,
                help_text="Models this team's Manager has restricted for their team, on top of whatever each member's Plan already allows - this only ever narrows access, never grants beyond the Plan (see governance/plans.py:effective_allowed_model_ids).",
                related_name="disabled_for_teams",
                to="chat.modelconfig",
            ),
        ),
    ]
