# Generated by Django 5.2.17 on 2026-09-04 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_team_disabled_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="region_restriction",
            field=models.CharField(
                choices=[("none", "No restrictions"), ("eu_only", "Only EU-hosted models allowed")],
                default="none",
                max_length=10,
            ),
        ),
    ]
