# Generated by Django 5.2.17 on 2026-09-04 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_department_region_restriction"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="retention_period",
            field=models.CharField(
                choices=[("30", "30 days"), ("90", "90 days"), ("2555", "7 years"), ("forever", "Forever")],
                default="forever",
                max_length=10,
            ),
        ),
    ]
