# Generated by Django 5.2.17 on 2026-09-12 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_user_mfa_enabled"),
        ("governance", "0023_plan_teams_included"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="departments",
                to="governance.plan",
            ),
        ),
    ]
