# Generated by Django 5.2.17 on 2026-09-20 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_seed_daily_backup_schedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="active_session_token",
            field=models.CharField(blank=True, default="", editable=False, max_length=64),
        ),
    ]
