# Generated by Django 5.2.17 on 2026-08-27 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("governance", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="systempromptversion",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
