# Generated by Django 5.2.17 on 2026-08-28 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("governance", "0002_alter_systempromptversion_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="usagelimit",
            name="allowed_file_extensions",
            field=models.CharField(
                blank=True,
                help_text="Comma-separated, no dots (e.g. pdf,png,txt). Leave blank to use the system default (pdf,txt,csv,md,png,jpg,jpeg,docx,xlsx,json).",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="usagelimit",
            name="max_upload_size_mb",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="File upload size cap in MB. Leave blank to use the system default (10MB).",
                null=True,
            ),
        ),
    ]
