# Generated by Django 5.2.17 on 2026-08-29 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_conversation_deleted_at_conversation_is_deleted_and_more"),
        ("governance", "0003_usagelimit_allowed_file_extensions_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_demo", models.BooleanField(default=False, help_text="Marks this as a time-limited trial plan.")),
                (
                    "demo_duration_days",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Only used when is_demo is set — days until this plan expires for a user.",
                        null=True,
                    ),
                ),
                ("daily_token_limit", models.PositiveIntegerField(blank=True, null=True)),
                ("monthly_token_limit", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "messages_per_session_limit",
                    models.PositiveIntegerField(
                        blank=True, help_text="Max user messages allowed in a single conversation.", null=True
                    ),
                ),
                (
                    "sessions_per_day_limit",
                    models.PositiveIntegerField(
                        blank=True, help_text="Max new conversations a user may start per day.", null=True
                    ),
                ),
                ("monthly_budget_cap", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                (
                    "feature_flags",
                    models.JSONField(blank=True, default=dict, help_text='e.g. {"file_upload": true, "export": true}'),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Inactive plans can't be newly assigned, but existing history is kept."
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="The plan new users are auto-assigned. Only one plan should have this set.",
                    ),
                ),
                (
                    "is_visible_to_admins",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this plan appears in the Change Plan picker, or stays hidden/archived.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("allowed_models", models.ManyToManyField(blank=True, related_name="plans", to="chat.modelconfig")),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="UpgradeRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("message", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("approved", "Approved"), ("dismissed", "Dismissed")],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "current_plan",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="governance.plan"
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="upgrade_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserPlanAssignment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, help_text="Set automatically for demo plans; blank = never expires.", null=True
                    ),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null if this was an automatic default assignment rather than an explicit admin action.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="assignments", to="governance.plan"
                    ),
                ),
                (
                    "previous_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="governance.plan",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan_assignment",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
