# Generated by Django 5.2.17 on 2026-08-29 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("governance", "0006_grandfather_existing_users_to_premium"),
    ]

    operations = [
        migrations.AddField(
            model_name="upgraderequest",
            name="requested_plan",
            field=models.ForeignKey(
                blank=True,
                help_text="Which plan the user asked to move to, if they specified one.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="governance.plan",
            ),
        ),
    ]
