# Generated by Django 5.2.17 on 2026-08-31 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("governance", "0007_upgraderequest_requested_plan"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="auto_upgrade_threshold_spend",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Reserved for future use (auto-suggest an upgrade past this spend). Not yet enforced anywhere.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="max_context_tokens",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Per-request cap on assembled prompt size (system prompt + history + attachments), distinct from daily_token_limit/monthly_token_limit which cap cumulative usage over time.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="max_requests_per_period",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Max messages allowed within one `period`. Null = no request-count cap.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="period",
            field=models.CharField(
                blank=True,
                choices=[("session", "Session"), ("day", "Day"), ("month", "Month")],
                help_text="Which window max_requests_per_period counts against.",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="feature_flags",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='e.g. {"file_upload": true, "export": true, "tools": true, "priority_queue": true, "long_context": true}',
            ),
        ),
    ]
