# Generated by Django 5.2.17 on 2026-08-31 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("governance", "0008_plan_auto_upgrade_threshold_spend_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoleFeatureToggle",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("role", models.CharField(max_length=20)),
                ("feature_key", models.CharField(max_length=50)),
                ("is_enabled", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("role", "feature_key"), name="unique_role_feature_toggle")
                ],
            },
        ),
    ]
