# Generated by Django 5.2.17 on 2026-09-03 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("governance", "0010_backfill_model_selection_flag"),
        ("providers", "0003_providermodel_tier"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="allowed_provider_models",
            field=models.ManyToManyField(blank=True, related_name="plans_v2", to="providers.providermodel"),
        ),
    ]
