# Generated by Django 5.2.17 on 2026-09-04 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("governance", "0011_plan_allowed_provider_models"),
        ("providers", "0005_providermodel_is_manager_assignable"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="auto_downgrade_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="plan",
            name="auto_downgrade_fallback_model",
            field=models.ForeignKey(
                blank=True,
                help_text="Model to force new replies onto once the threshold is crossed.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="providers.providermodel",
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="auto_downgrade_threshold_pct",
            field=models.PositiveSmallIntegerField(
                default=80, help_text="Percent of monthly_budget_cap spent before auto-downgrade kicks in."
            ),
        ),
    ]
