# Generated by Django 5.2.17 on 2026-09-04 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("governance", "0012_plan_auto_downgrade_enabled_and_more"),
        ("providers", "0005_providermodel_is_manager_assignable"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoutingRule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("code_like", "Task looks like code"),
                            ("casual_short", "Casual / short question"),
                            ("image_attached", "Image attached"),
                            ("long_document_attached", "Long document attached"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(
                        default=0, help_text="Lower runs first when more than one rule matches."
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "target_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routing_rules",
                        to="providers.providermodel",
                    ),
                ),
            ],
            options={
                "ordering": ["priority", "id"],
            },
        ),
    ]
