# Generated by Django 5.2.17 on 2026-09-04 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("governance", "0014_seed_retention_sweep_schedule"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComplianceSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("only_zero_retention_models", models.BooleanField(default=False)),
                ("pii_scanning_enabled", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Compliance settings",
                "verbose_name_plural": "Compliance settings",
            },
        ),
        migrations.CreateModel(
            name="PIIRule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("national_id", "CNIC / National ID numbers"),
                            ("credit_card", "Credit card numbers"),
                            ("phone_number", "Phone numbers"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[("block", "Block"), ("redact", "Redact"), ("warn", "Warn only")],
                        default="warn",
                        max_length=10,
                    ),
                ),
                ("is_enabled", models.BooleanField(default=False)),
            ],
        ),
    ]
