# Generated by Django 5.2.17 on 2026-09-06 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("governance", "0019_admin_keeps_default_standalone_tool_access"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="max_compare_uses_per_day",
            field=models.PositiveIntegerField(
                blank=True, help_text="Max Compare-mode (2-model) messages per day. Null = no limit.", null=True
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="max_domain_searches_per_day",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Overrides Domain Generator's global daily search limit for this plan. Null = use the global default.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="max_message_length",
            field=models.PositiveIntegerField(
                blank=True, help_text="Max characters allowed in a single message. Null = no limit.", null=True
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="max_playground_runs_per_day",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Overrides Code Playground's global daily run limit for this plan. Null = use the global default.",
                null=True,
            ),
        ),
    ]
