# Generated by Django 5.2.17 on 2026-09-08 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("governance", "0020_plan_max_compare_uses_per_day_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SecuritySettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("mfa_required_for_admins", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Security settings",
                "verbose_name_plural": "Security settings",
            },
        ),
    ]
