# Generated by Django 5.2.17 on 2026-09-08 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("governance", "0021_securitysettings"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteBranding",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("site_name", models.CharField(default="AI Client Portal", max_length=100)),
                ("tagline", models.CharField(blank=True, default="", max_length=200)),
                ("logo", models.ImageField(blank=True, null=True, upload_to="branding/")),
                ("favicon", models.ImageField(blank=True, null=True, upload_to="branding/")),
            ],
            options={
                "verbose_name": "Site branding",
                "verbose_name_plural": "Site branding",
            },
        ),
    ]
