# Generated by Django 5.2.17 on 2026-09-11 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("governance", "0022_sitebranding"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="teams_included",
            field=models.PositiveIntegerField(
                blank=True,
                default=1,
                help_text="Teams a department gets before being billed per extra team. Blank = unlimited.",
                null=True,
            ),
        ),
    ]
