# Generated by Django 5.2.17 on 2026-09-13 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("governance", "0024_rename_teams_included_plan_seats_included"),
    ]

    operations = [
        migrations.AddField(
            model_name="securitysettings",
            name="google_signin_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
