# Generated by Django 5.2.17 on 2026-09-13 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("governance", "0025_securitysettings_google_signin_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="monthly_document_reads_limit",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Max document (PDF/Word/Excel/text) attachments read per calendar month. Null = unlimited.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="monthly_image_reads_limit",
            field=models.PositiveIntegerField(
                blank=True, help_text="Max image attachments read per calendar month. Null = unlimited.", null=True
            ),
        ),
    ]
