# Generated by Django 5.2.17 on 2026-09-13 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("governance", "0026_plan_monthly_document_reads_limit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="monthly_media_generation_limit",
            field=models.PositiveIntegerField(
                blank=True,
                default=0,
                help_text="Max Grok-generated images+videos per calendar month, combined. 0 = not included; blank = unlimited.",
                null=True,
            ),
        ),
    ]
