# Generated by Django 5.2.17 on 2026-09-13 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("governance", "0027_plan_monthly_media_generation_limit"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="self_checkout_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Off shows 'Contact us' (creates an Upgrade Request) instead of an instant checkout button.",
            ),
        ),
    ]
