# Generated by Django 5.2.17 on 2026-09-13 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("governance", "0029_configure_demo_basic_advanced_full_capabilities"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="monthly_research_limit",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Max Research-mode (live web search) uses per calendar month. Null = unlimited.",
                null=True,
            ),
        ),
    ]
