# Generated by Django 5.2.17 on 2026-09-14 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("governance", "0032_fix_research_limit_for_plans_without_the_flag"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="billing_track",
            field=models.CharField(
                choices=[("per_user", "Per-User"), ("team", "Team")], default="per_user", max_length=10
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="is_most_popular",
            field=models.BooleanField(
                default=False,
                help_text="Highlights this plan with a 'Most popular' badge. Only one plan should have this set.",
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="show_on_public_pricing",
            field=models.BooleanField(
                default=True, help_text="Off hides this plan from the public /pricing/ page, even if Active."
            ),
        ),
    ]
