# Generated by Django 5.2.17 on 2026-09-17 14:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("governance", "0034_backfill_show_on_public_pricing"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["-timestamp"], name="auditlog_timestamp_idx"),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["action_type", "-timestamp"], name="auditlog_action_ts_idx"),
        ),
    ]
