# Generated by Django 5.2.17 on 2026-09-19 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("governance", "0035_auditlog_auditlog_timestamp_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="max_messages_per_minute",
            field=models.PositiveIntegerField(
                blank=True, help_text="Max chat messages within any 60-second window. Null = no burst cap.", null=True
            ),
        ),
    ]
