# Generated by Django 5.2.17 on 2026-09-19 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("governance", "0036_plan_max_messages_per_minute"),
    ]

    operations = [
        migrations.AddField(
            model_name="userplanassignment",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
