# Generated by Django 5.2.17 on 2026-09-21 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("governance", "0037_userplanassignment_cancelled_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitebranding",
            name="custom_config",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="sitebranding",
            name="custom_logo_dark",
            field=models.ImageField(blank=True, null=True, upload_to="branding/"),
        ),
        migrations.AddField(
            model_name="sitebranding",
            name="custom_logo_light",
            field=models.ImageField(blank=True, null=True, upload_to="branding/"),
        ),
        migrations.AddField(
            model_name="sitebranding",
            name="preset",
            field=models.CharField(
                choices=[
                    ("branding_1", "Branding 1"),
                    ("branding_2", "Branding 2"),
                    ("branding_3", "Branding 3"),
                    ("custom", "Custom"),
                ],
                default="branding_1",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="sitebranding",
            name="version",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
