# Generated by Django 5.2.17 on 2026-08-29 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_seed_daily_expiry_sweep_schedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationpreference",
            name="email_model_sync_available",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("usage_warning", "Usage limit warning"),
                    ("plan_change", "Plan changed"),
                    ("trial_expiring", "Trial expiring soon"),
                    ("trial_expired", "Trial expired"),
                    ("admin_change", "Admin changed your account"),
                    ("model_sync_available", "New models available to sync"),
                ],
                max_length=30,
            ),
        ),
    ]
