# Generated by Django 5.2.17 on 2026-09-05 14:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_notificationpreference_email_model_sync_available_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("recipient", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=255)),
                ("status", models.CharField(choices=[("sent", "Sent"), ("failed", "Failed")], max_length=10)),
                ("error_message", models.TextField(blank=True)),
                ("tracking_token", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("opened_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EmailSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("host", models.CharField(blank=True, max_length=255)),
                ("port", models.PositiveIntegerField(default=587)),
                ("encryption", models.CharField(choices=[("tls", "TLS"), ("ssl", "SSL")], default="tls", max_length=5)),
                ("username", models.CharField(blank=True, max_length=255)),
                ("password_encrypted", models.BinaryField(blank=True, default=b"")),
                ("from_address", models.EmailField(blank=True, max_length=254)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unverified", "Saved — not tested yet"),
                            ("connected", "Verified working"),
                            ("failed", "Connection failed"),
                            ("stale", "Config changed — retest needed"),
                        ],
                        default="unverified",
                        max_length=12,
                    ),
                ),
                ("last_test_error", models.TextField(blank=True)),
                ("last_tested_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Email settings",
                "verbose_name_plural": "Email settings",
            },
        ),
    ]
