# Generated by Django 5.2.17 on 2026-09-05 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0004_emaillog_emailsettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="email_account_created",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("usage_warning", "Usage limit warning"),
                    ("plan_change", "Plan changed"),
                    ("trial_expiring", "Trial expiring soon"),
                    ("trial_expired", "Trial expired"),
                    ("admin_change", "Admin changed your account"),
                    ("model_sync_available", "New models available to sync"),
                    ("account_created", "Account created"),
                ],
                max_length=30,
            ),
        ),
    ]
