# Generated by Django 5.2.17 on 2026-09-19 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0007_notification_notif_user_is_read_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationpreference",
            name="email_refund_decision",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="email_refund_requested",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("usage_warning", "Usage limit warning"),
                    ("plan_change", "Plan changed"),
                    ("trial_expiring", "Trial expiring soon"),
                    ("trial_expired", "Trial expired"),
                    ("admin_change", "Admin changed your account"),
                    ("model_sync_available", "New models available to sync"),
                    ("account_created", "Account created"),
                    ("invoice_payment_submitted", "Invoice payment submitted"),
                    ("refund_requested", "Refund requested"),
                    ("refund_decision", "Refund request decision"),
                ],
                max_length=30,
            ),
        ),
    ]
