# Generated by Django 5.2.17 on 2026-09-21 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0010_maintenance_window"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("usage_warning", "Usage limit warning"),
                    ("plan_change", "Plan changed"),
                    ("trial_expiring", "Trial expiring soon"),
                    ("trial_expired", "Trial expired"),
                    ("admin_change", "Admin changed your account"),
                    ("model_sync_available", "New models available to sync"),
                    ("account_created", "Account created"),
                    ("invoice_payment_submitted", "Invoice payment submitted"),
                    ("refund_requested", "Refund requested"),
                    ("refund_decision", "Refund request decision"),
                    ("plan_cancellation", "Plan cancellation"),
                    ("maintenance", "Maintenance"),
                    ("new_trusted_device", "New trusted device"),
                ],
                max_length=30,
            ),
        ),
    ]
